config/routes.rb
Brevidy::Application.routes.draw do
  # Domain Route
  root :to => 'users#new'
  
  # Session / Authentication Routes
  resources :sessions, :only => [:create]
  match :login, :to => 'sessions#new'
  match :logout, :to => 'sessions#destroy'
  match :signup, :to => 'users#signup'
  match "/auth/:provider/callback", :to => "sessions#create_social_session"
  match "/auth/failure", :to => "errors#error_social_auth"
  match "/auth/deauthorize", :to => "social_networks#deauthorize"
  match 'account/forgotten_password', :to => 'users#forgotten_password', :as => :forgotten_password, :via => [:get]
  match 'account/validate_forgotten_password', :to => 'users#validate_forgotten_password', :as => :validate_forgotten_password, :via => [:post]
  
  # Explore Routes
  match :explore, :to => 'videos#explore', :via => [:get] # aka the popular videos page
  #match 'explore/suggested_channels', :to => 'videos#suggested_channels', :as => :suggested_channels, :via => [:get]
  #match 'explore/recent', :to => 'videos#recent', :as => :recent_videos, :via => [:get]
  match 'explore/users', :to => 'users#index', :as => :find_people, :via => [:get]
  
  # Invitation Route
  match 'invitations/:invitation_token', :to => 'users#new', :as => :signup_via_invitation, :via => [:get]
  
  # Search Routes
  match 'search/videos', :to => 'search#videos', :as => :video_search, :via => [:get]
  match 'search/users', :to => 'search#users', :as => :user_search, :via => [:get]
  
  # Public Video / Channel Routes
  match 'p/:public_token', :to => 'public_videos#show', :as => :public_video, :via => [:get]
  match 'embed/:public_token', :to => 'public_videos#embed', :as => :embed_video, :via => [:get]
  match 'c/:public_token', :to => 'channels#show_by_token_access', :as => :public_channel, :via => [:get]
  
  # People You May Know Route
  # match 'users/people_you_may_know', :to => 'users#people_you_may_know', :as => :people_you_may_know, :via => [:get]

  # Public Page Routes such as Contact, Privacy, etc
  match 'help/faq', :to => 'public#faq', :via => [:get], :as => :faq
  match 'help/video_faq', :to => 'public#video_faq', :via => [:get], :as => :video_faq
  match 'help/video_guidelines', :to => 'public#video_guidelines', :via => [:get], :as => :video_guidelines 
  match 'help/contact', :to => 'public#contact', :via => [:get], :as => :contact
  match 'help/privacy', :to => 'public#privacy', :via => [:get], :as => :privacy
  match 'help/tos', :to => 'public#tos', :via => [:get], :as => :tos

  # Users Create
  resources :users, :only => [:create]
  
  # Username Availability
  match :username_availability, :to => 'users#username_availability', :via => [:get]
  
  # This needs to go at the bottom of this routes.rb file to catch 
  # all routes that didn't match the routes specified above.
  #
  ## This regex constraint handles these cases: http://rubular.com/r/PiP1nTNph2
  ### alphanumeric with underscores only; can't have consecutive underscores; can't be only an underscore;
  ### can be only a letter; can't start with a number or be only a number; can't contain spaces; can end in an underscore;
  ### can't be only an underscore and numbers (if it starts with an underscore, the next char must be a letter)
  controller :users, :path => '/:username', :as => :user, :constraints => { :username => /_?[a-z]_?(?:[a-z0-9]_?)*/i } do
    resources :badges, :only => [:index]
    resources :channels do
      match :request_access, :to => 'subscriptions#handle_access_request', :via => [:get]
      match :subscribe, :to => 'subscriptions#create', :via => [:post]
      match :unsubscribe, :to => 'subscriptions#destroy', :via => [:delete]
      match :remove_subscriber, :to => 'subscriptions#remove_subscriber', :via => [:delete]
    end
    match :about, :to => 'profile#index', :via => [:get]
    match 'about/update/:id', :to => 'profile#update', :as => :update_about, :via => [:put]
    resources :videos, :except => [:create, :index] do
      resources :badges, :only => [:create, :destroy]
      match 'badges', :to => 'badges#badges_dialog', :as => :badges_dialog, :via => [:get]
      resources :comments, :only => [:create, :destroy]  
      get :embed_code
      match :flag, :to => 'videos#flag', :via => [:post]
      match '/flag/dialog', :to => 'videos#flag_video_dialog', :as => :flag_dialog, :via => [:get]
      match :share_via_email, :to => 'videos#share_via_email'
      resources :tags, :only => [:destroy]
      
      # uploading routes
      post :encoder_callback
      put :successful_upload
      put :upload_error    
    end
    resources :social_networks, :only => [:destroy]
    
    # All matched routes that are nested under User go here
    match '/', :to => 'users#show', :via => [:get]
    match :edit_banner, :to => 'users#edit_banner', :via => [:get]
    match :invite_people, :to => 'invitation_link#create'
    match :invitations, :to => 'invitation_link#index'
    match :latest_activity, :to => 'user_events#show', :via => [:get]
    match 'add_to_channel/dialog', :to => 'videos#add_to_channel_dialog', :as => :add_to_channel_dialog, :via => [:get]
    match 'add_to_channel', :to => 'videos#add_to_channel', :as => :add_to_channel, :via => [:post]
    match 'share/dialog', :to => 'videos#share_dialog', :as => :share_dialog, :via => [:get]
    match 'share', :to => 'videos#share', :as => :create_shared_video, :via => [:post]
    match :edit_featured_videos, :to => 'channels#edit_featured_videos', :via => [:get]
    match :update_featured_videos, :to => 'channels#update_featured_videos', :via => [:put]
    match 'stream', :to => 'users#subscriptions_stream'
    match :account, :to => 'users#edit'
    match 'account/update', :to => 'users#update', :via => [:put]
    match 'account/image', :to => 'users#new_image', :via => [:put]
    match 'account/image_status', :to => 'users#new_image_status', :via => [:get]
    match :update_banner_from_gallery, :to => 'users#update_banner_from_gallery', :via => [:put]
    match :update_background_image, :to => 'users#update_background_image', :via => [:put]
    match 'account/password', :to => 'users#update_password', :via => [:put]
    match 'account/birthday', :to => 'users#update_birthday', :via => [:put]
    match 'account/notifications', :to => 'users#update_notifications', :via => [:put]
    match :subscriptions, :to => 'subscriptions#subscriptions'
    match :subscribers, :to => 'subscriptions#subscribers'
    match :block, :to => 'users#block'
    match :unblock, :to => 'users#unblock'
    match :validate_reset_password, :to => 'users#validate_reset_password', :via => [:get]
    match :reset_password, :to => 'users#reset_password', :via => [:post]
  end

  # Catches all bad routes that weren't matched with the above routes and shows 404 page instead
  match '*a', :to => 'errors#routing'
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  include ApplicationHelper
  
  before_filter :site_authenticate, :except => [:index, :show, :show_by_token_access]
  before_filter :set_user, :except => [:show_by_token_access]
  before_filter :verify_current_user_is_not_blocked, :only => [:index]
  before_filter :set_channel, :only => [:edit, :destroy, :show, :update]
  before_filter :verify_user_owns_channel, :only => [:destroy, :edit, :update]
  before_filter :set_featured_videos, :only => [:edit, :edit_featured_videos, :index, :show]
  before_filter :verify_user_can_access_channel, :only => [:show]
  
  # GET /:username/channels/:id-slug-name-goes-here/edit
  def edit
    @subscribers = @channel.subscribers_as_people.paginate(:page => params[:page], :per_page => 100)
    
    respond_to do |format|
      params[:page].to_i > 1 ? format.js : format.html
    end
  end
  
  # GET /:username/edit_featured_videos
  def edit_featured_videos
    # Do a quick security check to verify user
    render(:template => "errors/error_404", :status => 404) and return unless current_user?(@user)
    
    @featured_videos = current_user.featured_videos.paginate(:page => params[:page], :per_page => 20, :order => 'featured_at DESC')
    
    respond_to do |format|
      params[:page].to_i > 1 ? format.js : format.html
    end
  end
  
  # DELETE /:username/channels/:id-slug-name-goes-here
  def destroy
    if @channel.featured?
      render :json => {:error => "You cannot delete your featured channel."}, :status => :unauthorized
    else
      @channel.destroy and redirect_to user_channels_path(current_user)
    end
  end
  
  # GET /:username/channels
  def index  
    @channels = @user.channels.paginate(:page => params[:page], :per_page => 9, :order => 'created_at DESC')
    
    respond_to do |format|
      params[:page].to_i > 1 ? format.js : format.html
    end
  end
  
  # GET /:username/channels/:id-slug-name-goes-here
  def show    
    if current_user.blank? || !current_user?(@user)
      # Only show videos that are in a :ready state
      @videos ||= @channel.videos.joins(:video_graph).where(:video_graphs => { :status => VideoGraph.get_status_number(:ready) }).
                           paginate(:page => params[:page], :per_page => 10, :order => 'created_at DESC')
    else    
      # Show all videos except ones that are uploading
      @videos ||= @channel.videos.joins(:video_graph).where(:video_graphs => { :status => Video.statuses_to_show_to_current_user }).
                           paginate(:page => params[:page], :per_page => 10, :order => 'created_at DESC')
    end
      
    respond_to do |format|
      params[:page].to_i > 1 ? format.js : format.html
    end
  end
  
  # GET /c/:public_token
  def show_by_token_access
    if params[:public_token]
      # Only accept the first 50 characters as the public token
      @channel ||= Channel.where('public_token = ?', params[:public_token].strip.first(50)).first
      
      if @channel
        @viewing_via_token_access = true
        @user = get_object_owner(@channel)
        @latest_featured_videos = @user.featured_videos.limit(4)
        # Only show videos that are in a :ready state
        @videos ||= @channel.videos.joins(:video_graph).where(:video_graphs => { :status => VideoGraph.get_status_number(:ready) }).
                             paginate(:page => params[:page], :per_page => 10, :order => 'created_at DESC')
                           
        respond_to do |format|
          params[:page].to_i > 1 ? format.js { render 'channels/show.js' } : format.html { render 'channels/show.html' }
        end
      else
        # show an error page if we couldn't find the channel
        render :template => "errors/error_404", :status => 404
      end
    else
      # no public token passed in
      render :template => "errors/error_404", :status => 404
    end
  end
  
  # PUT /:username/channels/:id-slug-name-goes-here/update
  def update
    # Update privacy params
    if params[:privacy]
      @channel.private = params[:privacy]
      send_back_link = true
    end
    
    # Update name
    if params[:title]
      @channel.title = params[:title]
    end
    
    if @channel.save
      if send_back_link
        render :json => { :new_link => user_channel_url(@user, @channel, :privacy => @channel.private? ? "false" : "true") }, 
               :status => :accepted
      else
        render :nothing => true, :status => :accepted
      end
    else
      render :json => { :error => get_errors_for_class(@channel).to_sentence }, 
             :status => :unprocessable_entity
    end
  end
  
  # PUT /:username/update_featured_videos
  def update_featured_videos
    @video ||= current_user.videos.find_by_id(params[:video_id])
    if @video
      if @video == current_user.featured_videos.first
        render :json => { :error => "That video is already at the top of your featured videos list :)" }, 
               :status => :unprocessable_entity
      else
        @video.featured_at = Time.now
        @video.save
        render :json => { :featured_video => render_to_string( :partial => 'shared/featured_video.html',
                                                               :locals => { :featured_video => @video }) }, 
               :status => :accepted
      end
    else
      render :json => { :error => "Either that video does not exist or you do not have permission to move it." }, 
             :status => :unprocessable_entity
    end
  end
  
end

app/views/channels/_button_subscribe.html.haml
- link_text = is_private ? "Request Access" : "Subscribe"
= link_to(link_text, user_channel_subscribe_path(get_object_owner(channel), channel, :ref => button_size), :class => "subscribe btn #{button_size}", :remote => true, :method => "POST")

app/views/channels/_button_unsubscribe.html.haml
= link_to("Subscribed", user_channel_unsubscribe_path(get_object_owner(channel), channel, :ref => button_size), :class => "unsubscribe btn success #{button_size}", :remote => true, :method => "DELETE")

app/views/channels/_channel.html.haml
- # For the "content_for" blocks, you must key off the channel ID
- # otherwise it will keep appending data to a regular symbol like :channel_view
- # so by the time you get to the 2nd or 3rd channel, you will have 2 or 3 sets
- # of channel data attached to the "content_for" store

- channel_owner = get_object_owner(channel)

- content_for "channel_view_#{channel.id}" do
  - if controller.controller_name == 'subscriptions' && controller.action_name == 'subscriptions'
    .subscriptions-view
      = link_to(user_path(channel_owner)) do
        = image_tag("#{channel_owner.image.blank? ? 'default_user_35px.jpg' : channel_owner.image_url(:small_profile) }", 
          :alt => "#{channel_owner.name}",
          :size => "35x35")
      
      .meta-area
        %h5
          = link_to(user_channel_path(channel_owner, channel), :class => "lighten-to-blue") do
            #{channel.title}
        %p
          = link_to(user_path(channel_owner), :class => "lighten-to-blue") do
            by #{channel_owner.name}
    
  - else
    %h5
      - if channel.featured?
        = image_tag("featured_star.png", :alt => "Featured Channel", :size => "16x16")
      - elsif channel.private?
        = image_tag("private_small.png", :alt => "Private Channel", :size => "16x16")
      - else
        = image_tag("public.png", :alt => "Public Channel", :size => "16x16")
    
      = link_to(user_channel_path(channel_owner, channel), :class => "lighten-to-blue") do
        #{channel.title}
  
  - # Thumbnail view
  = link_to(user_channel_path(channel_owner, channel), :class => "channel-thumbnail-area") do
    .thumbnails
      - most_recent_videos = channel.videos_for_preview
      - most_recent_videos.each do |v|
        .thumb-view
          = image_tag(v.get_thumbnail_url(v.selected_thumbnail), :alt => v.title, :size => "190x102")
      
- content_for "private_channel_message_#{channel.id}" do
  - if controller.controller_name == 'subscriptions' && controller.action_name == 'subscriptions'
    .subscriptions-view
      = link_to(user_path(channel_owner)) do
        = image_tag("#{channel_owner.image.blank? ? 'default_user_35px.jpg' : channel_owner.image_url(:small_profile) }", 
          :alt => "#{channel_owner.name}",
          :size => "35x35")
    
      .meta-area
        %h5
          #{channel.title}
        %p
          = link_to(user_path(channel_owner), :class => "lighten-to-blue") do
            by #{channel_owner.name}
  - else        
    %h5
      = image_tag("private_small.png", :alt => "Private Channel", :size => "16x16")
      #{channel.title}
  
  = render :partial => "channels/private_area_message"

.channel-wrapper{"data-channel-id" => channel.id}
  - # Channel Content Area  
  - if current_user_owns?(channel)
    = content_for "channel_view_#{channel.id}"
  - elsif channel.private?
    - if current_user.blank?
      = content_for "private_channel_message_#{channel.id}"
    - else
      - if current_user.is_subscribed_to?(channel)
        = content_for "channel_view_#{channel.id}"
      - else
        = content_for "private_channel_message_#{channel.id}"
  - else
    = content_for "channel_view_#{channel.id}"

  
  .button-area
    - if current_user_owns?(channel)
      = link_to("Manage Channel", edit_user_channel_path(channel_owner, channel), :class => "btn xlarge")
    - else
      - if current_user.blank?
        = link_to("Login to Subscribe", root_path, :class => "btn xlarge")
      - else
        - if current_user.is_subscribed_to?(channel)
          = render :partial => "channels/button_unsubscribe", :locals => { :user => channel_owner, :channel => channel, :button_size => 'xlarge' }
        - else
          - if channel.private?
            = render :partial => "channels/button_subscribe", :locals => { :user => channel_owner, :channel => channel, :is_private => true, :button_size => 'xlarge' }
          - else
            = render :partial => "channels/button_subscribe", :locals => { :user => channel_owner, :channel => channel, :is_private => false, :button_size => 'xlarge' }

app/views/channels/_featured_video.html.haml
.featured-video-post{"data-video-id" => "#{featured_video.id}"}
  .update-position-area
    .move-to-top
      = link_to(user_update_featured_videos_path(current_user, :video_id => featured_video.id), :class => "move-video-to-top", 
                                                "data-video-id" => "#{featured_video.id}", :remote => true, :method => "PUT") do
                                                
        = image_tag("up_arrow.png", :size => "20x10", :alt => "Move to Top")
        Move to Top

  .thumbnail
    = image_tag(featured_video.get_thumbnail_url(featured_video.selected_thumbnail), :alt => featured_video.title, :size => "190x102")
    
  .featured-video-meta-area
    %h3 
      = featured_video.title
      
    %span.label.important Featured

    %span.gray
      #{time_ago_in_words(featured_video.featured_at)} ago
  

app/views/channels/_private_area_message.html.haml
.private-channel-message
  = image_tag("private_large.png", :alt => "This channel is private", :size => "117x110")
  %p
    This channel is private.
    %br/
    %br/
    You need to request access to view any videos in this channel.

app/views/channels/_private_channel_link.html.haml
%a{:href => "mailto:?body=#{public_channel_url(:public_token => channel.public_token)}&subject=#{channel.title}"}
  Want to share this private channel?  You can give your friends or family this link:
%p{:class => defined?(with_margin) ? "mhxl" : ""}=public_channel_url(:public_token => channel.public_token)

app/views/channels/_subscriber.html.haml
%li.zebra-striped
  = link_to(user_path(subscriber), :class => "user-image") do
    = image_tag("#{subscriber.image.blank? ? 'default_user_50px.jpg' : subscriber.image_url(:medium_profile) }", 
      :alt => "#{subscriber.name}",
      :size => "50x50")
  
  .user-meta
    = link_to(subscriber.name, user_path(subscriber))
    
    .buttons
      = link_to("Remove", user_channel_remove_subscriber_path(@user, @channel, :user_id => subscriber.id), :class => "small btn remove-subscriber")
      = link_to("Block", user_block_path(subscriber), :class => "block-user small btn")

app/views/channels/edit.js.haml
= render :partial => 'subscriber', :collection => @subscribers

app/views/channels/edit_featured_videos.html.haml
- # User Banner Image
= render 'users/top_banner'

- # Middle User Info Section
= render 'users/middle_user_banner'

- # Dark Content Wrapper
.lower-wrapper
  = render 'users/featured_videos'
  
  - # Main (White) Content Wrapper
  .content-wrapper
    = render 'shared/content_titles'
    
    - if @featured_videos.blank?
      .info-message.mhl
        You have not added any videos to your Featured Videos channel.  Please add some and then come back to edit their order.
    - else    
      = render :partial => 'channels/featured_video', :collection => @featured_videos
    
      = will_paginate @featured_videos
    
      = render :partial => "shared/infinite_scrolling", :locals => { :item_selector => ".featured-video-post" }
    
    
- # Tell the page to scroll down to the content wrapper upon page load
= render 'shared/scroll_to_content_wrapper'

app/views/channels/edit_featured_videos.js.haml
= render :partial => 'channels/featured_video', :collection => @featured_videos

app/views/channels/index.html.haml
- # User Banner Image
= render 'users/top_banner'

- # Middle User Info Section
= render 'users/middle_user_banner'

- # Dark Content Wrapper
.lower-wrapper
  = render 'users/featured_videos'
  
  - # Main (White) Content Wrapper
  .content-wrapper
    = render 'shared/content_titles'
  
    = render @channels
    
    = will_paginate @channels
    
    = render :partial => "shared/infinite_scrolling", :locals => { :item_selector => ".channel-wrapper" }
    
- # Tell the page to scroll down to the content wrapper upon page load
= render 'shared/scroll_to_content_wrapper'

app/views/channels/index.js.haml
= render @channels

app/views/channels/show.html.haml
- # User Banner Image
= render 'users/top_banner'

- # Middle User Info Section
= render 'users/middle_user_banner'

- # Dark Content Wrapper
.lower-wrapper
  = render 'users/featured_videos'
  
  - # Main (White) Content Wrapper
  .content-wrapper
    = render 'shared/content_titles'
  
    .info-message.mhl.clearfix.channel-show-info
      %span.pull-left
        Now viewing: #{@channel.title}
      
      .pull-right 
        - if current_user_owns?(@channel)
          = link_to(edit_user_channel_path(@user, @channel), :class => "small btn") do
            = image_tag("edit_icon.png", :size => "11x11")
            Manage Channel
          
        - else
          - if current_user.blank?
            = link_to("Login to Subscribe", root_path, :class => "btn small")
          - else
            - if current_user.is_subscribed_to?(@channel)
              = render :partial => "channels/button_unsubscribe", :locals => { :user => @user, :channel => @channel, :button_size => 'small' }
            - else
              - if @channel.private?
                = render :partial => "channels/button_subscribe", :locals => { :user => @user, :channel => @channel, :is_private => true, :button_size => 'small' }
              - else
                = render :partial => "channels/button_subscribe", :locals => { :user => @user, :channel => @channel, :is_private => false, :button_size => 'small' }
        
      .clear
        - if current_user_owns?(@channel) and @channel.private?
          = render :partial => "private_channel_link", :locals => { :channel => @channel, :with_margin => true }
    

      - if @viewing_via_token_access
        %input{:name => "channel_access_token", :type => "hidden", :value => "#{@channel.public_token}"}/
      
    - if @videos.blank?
      .info-message.mhl
        There are no videos in this channel to show.
    - else        
      = render @videos
    
      = will_paginate @videos
    
      = render :partial => "shared/infinite_scrolling", :locals => { :item_selector => ".video-post" }

app/views/channels/show.js.haml
= render @videos