config/routes.rb
Brevidy::Application.routes.draw do
  # Domain Route
  root :to => 'users#new'
  
  # Session / Authentication Routes
  resources :sessions, :only => [:create]
  match :login, :to => 'sessions#new'
  match :logout, :to => 'sessions#destroy'
  match :signup, :to => 'users#signup'
  match "/auth/:provider/callback", :to => "sessions#create_social_session"
  match "/auth/failure", :to => "errors#error_social_auth"
  match "/auth/deauthorize", :to => "social_networks#deauthorize"
  match 'account/forgotten_password', :to => 'users#forgotten_password', :as => :forgotten_password, :via => [:get]
  match 'account/validate_forgotten_password', :to => 'users#validate_forgotten_password', :as => :validate_forgotten_password, :via => [:post]
  
  # Explore Routes
  match :explore, :to => 'videos#explore', :via => [:get] # aka the popular videos page
  #match 'explore/suggested_channels', :to => 'videos#suggested_channels', :as => :suggested_channels, :via => [:get]
  #match 'explore/recent', :to => 'videos#recent', :as => :recent_videos, :via => [:get]
  match 'explore/users', :to => 'users#index', :as => :find_people, :via => [:get]
  
  # Invitation Route
  match 'invitations/:invitation_token', :to => 'users#new', :as => :signup_via_invitation, :via => [:get]
  
  # Search Routes
  match 'search/videos', :to => 'search#videos', :as => :video_search, :via => [:get]
  match 'search/users', :to => 'search#users', :as => :user_search, :via => [:get]
  
  # Public Video / Channel Routes
  match 'p/:public_token', :to => 'public_videos#show', :as => :public_video, :via => [:get]
  match 'embed/:public_token', :to => 'public_videos#embed', :as => :embed_video, :via => [:get]
  match 'c/:public_token', :to => 'channels#show_by_token_access', :as => :public_channel, :via => [:get]
  
  # People You May Know Route
  # match 'users/people_you_may_know', :to => 'users#people_you_may_know', :as => :people_you_may_know, :via => [:get]

  # Public Page Routes such as Contact, Privacy, etc
  match 'help/faq', :to => 'public#faq', :via => [:get], :as => :faq
  match 'help/video_faq', :to => 'public#video_faq', :via => [:get], :as => :video_faq
  match 'help/video_guidelines', :to => 'public#video_guidelines', :via => [:get], :as => :video_guidelines 
  match 'help/contact', :to => 'public#contact', :via => [:get], :as => :contact
  match 'help/privacy', :to => 'public#privacy', :via => [:get], :as => :privacy
  match 'help/tos', :to => 'public#tos', :via => [:get], :as => :tos

  # Users Create
  resources :users, :only => [:create]
  
  # Username Availability
  match :username_availability, :to => 'users#username_availability', :via => [:get]
  
  # This needs to go at the bottom of this routes.rb file to catch 
  # all routes that didn't match the routes specified above.
  #
  ## This regex constraint handles these cases: http://rubular.com/r/PiP1nTNph2
  ### alphanumeric with underscores only; can't have consecutive underscores; can't be only an underscore;
  ### can be only a letter; can't start with a number or be only a number; can't contain spaces; can end in an underscore;
  ### can't be only an underscore and numbers (if it starts with an underscore, the next char must be a letter)
  controller :users, :path => '/:username', :as => :user, :constraints => { :username => /_?[a-z]_?(?:[a-z0-9]_?)*/i } do
    resources :badges, :only => [:index]
    resources :channels do
      match :request_access, :to => 'subscriptions#handle_access_request', :via => [:get]
      match :subscribe, :to => 'subscriptions#create', :via => [:post]
      match :unsubscribe, :to => 'subscriptions#destroy', :via => [:delete]
      match :remove_subscriber, :to => 'subscriptions#remove_subscriber', :via => [:delete]
    end
    match :about, :to => 'profile#index', :via => [:get]
    match 'about/update/:id', :to => 'profile#update', :as => :update_about, :via => [:put]
    resources :videos, :except => [:create, :index] do
      resources :badges, :only => [:create, :destroy]
      match 'badges', :to => 'badges#badges_dialog', :as => :badges_dialog, :via => [:get]
      resources :comments, :only => [:create, :destroy]  
      get :embed_code
      match :flag, :to => 'videos#flag', :via => [:post]
      match '/flag/dialog', :to => 'videos#flag_video_dialog', :as => :flag_dialog, :via => [:get]
      match :share_via_email, :to => 'videos#share_via_email'
      resources :tags, :only => [:destroy]
      
      # uploading routes
      post :encoder_callback
      put :successful_upload
      put :upload_error    
    end
    resources :social_networks, :only => [:destroy]
    
    # All matched routes that are nested under User go here
    match '/', :to => 'users#show', :via => [:get]
    match :edit_banner, :to => 'users#edit_banner', :via => [:get]
    match :invite_people, :to => 'invitation_link#create'
    match :invitations, :to => 'invitation_link#index'
    match :latest_activity, :to => 'user_events#show', :via => [:get]
    match 'add_to_channel/dialog', :to => 'videos#add_to_channel_dialog', :as => :add_to_channel_dialog, :via => [:get]
    match 'add_to_channel', :to => 'videos#add_to_channel', :as => :add_to_channel, :via => [:post]
    match 'share/dialog', :to => 'videos#share_dialog', :as => :share_dialog, :via => [:get]
    match 'share', :to => 'videos#share', :as => :create_shared_video, :via => [:post]
    match :edit_featured_videos, :to => 'channels#edit_featured_videos', :via => [:get]
    match :update_featured_videos, :to => 'channels#update_featured_videos', :via => [:put]
    match 'stream', :to => 'users#subscriptions_stream'
    match :account, :to => 'users#edit'
    match 'account/update', :to => 'users#update', :via => [:put]
    match 'account/image', :to => 'users#new_image', :via => [:put]
    match 'account/image_status', :to => 'users#new_image_status', :via => [:get]
    match :update_banner_from_gallery, :to => 'users#update_banner_from_gallery', :via => [:put]
    match :update_background_image, :to => 'users#update_background_image', :via => [:put]
    match 'account/password', :to => 'users#update_password', :via => [:put]
    match 'account/birthday', :to => 'users#update_birthday', :via => [:put]
    match 'account/notifications', :to => 'users#update_notifications', :via => [:put]
    match :subscriptions, :to => 'subscriptions#subscriptions'
    match :subscribers, :to => 'subscriptions#subscribers'
    match :block, :to => 'users#block'
    match :unblock, :to => 'users#unblock'
    match :validate_reset_password, :to => 'users#validate_reset_password', :via => [:get]
    match :reset_password, :to => 'users#reset_password', :via => [:post]
  end

  # Catches all bad routes that weren't matched with the above routes and shows 404 page instead
  match '*a', :to => 'errors#routing'
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  require 'securerandom'

  # needed for truncate method
  include ActionView::Helpers::TextHelper
  
  before_filter :site_authenticate, :only => [:block, :edit, :edit_banner, :latest_activity, :new_image, 
                                              :new_image_status, :subscriptions_stream, :unblock, :update, 
                                              :update_background_image, :update_banner_from_gallery, :update_notifications, 
                                              :update_password]
  before_filter :redirect_to_stream_if_logged_in, :only => [:create, :forgotten_password, :new, :reset_password, :signup, 
                                                            :validate_forgotten_password, :validate_reset_password] 
  before_filter :set_user, :except => [:create, :forgotten_password, :index, :new, :signup, :username_availability, :validate_forgotten_password]
  before_filter :verify_current_user_is_not_blocked, :only => [:show]
  before_filter :verify_user_owns_page, :only => [:edit, :edit_banner, :new_image, :new_image_status, :subscriptions_stream, 
                                                  :update, :update_background_image, :update_banner_from_gallery, :update_notifications, 
                                                  :update_password]
  before_filter :set_featured_videos, :only => [:show, :subscriptions_stream]
  before_filter :verify_tokens_match_and_token_is_fresh, :only => [:reset_password, :validate_reset_password]
  
  # Caching
  caches_action :new
  
  # POST /:username/block
  def block
    blocking = Blocking.where(:requesting_user => current_user.id, :blocked_user => @user.id).first
    if blocking
      render :json => { :error => "You are already blocking that user." }, 
             :status => :unprocessable_entity
    else
      current_user.block!(@user)
      render :nothing => true, :status => :created
    end
  end
  
  # POST /users
  def create
    @user = User.new(params[:user])

    if @user.save
      sign_in @user
      
      # associate them w/ a social login account if necessary
      unless params[:social_signup].blank?
        @user.associate_with_social_account(params, cookies[:social_image_url], cookies[:social_bio])
      end
      
      respond_to do |format|
        format.html { redirect_to user_stream_path(current_user) }
        format.json { render :json => { :success => true, 
                                        :message => nil,
                                        :user_id => @user.id }, :status => :created }
      end
      
      UserMailer.delay.celebrate_new_user(@user) if Rails.env.production?
    else
      # return errors via AJAX
      respond_to do |format|
        format.js
        format.json { render :json => { :success => false, 
                                        :message => get_errors_for_class(@user).to_sentence,
                                        :user_id => false }, :status => :unprocessable_entity }
      end
    end
  end
  
  # GET /:username/account
  def edit
    @browser_title ||= "Edit Account"
    @facebook_connected = SocialNetwork.find_by_user_id_and_provider(current_user.id, "facebook") 
    @twitter_connected = SocialNetwork.find_by_user_id_and_provider(current_user.id, "twitter") 
  end
  
  # GET /:username/edit_banner
  def edit_banner
    @banner_images = BannerImage.where(:active => true)
  end
  
  # GET /account/forgotten_password
  def forgotten_password
    @browser_title ||= "Forgotten Password"
    @show_password_reset = false
 
    respond_to do |format|
      format.html { render(:template => "users/forgotten_password", :status => :ok, :layout => "signed_out") }
    end
  end
  
  # GET /users
  def index
    @browser_title ||= "Find People"
    
    # show the 4 latest featured videos for the Explore page
    #@latest_featured_videos = User.find_by_username("brevidy").featured_videos.limit(4)
    
    @latest_featured_videos = []
    
    respond_to do |format|
      format.html
    end
  end
  
  # Main landing page w/ social sign up buttons
  # GET brevidy.com
  def new
    @invitation ||= InvitationLink.handle_invite_token(params[:invitation_token])
    cookies[:invitation_token] = params[:invitation_token] if params[:invitation_token]
    
    respond_to do |format|
      format.html { render(:template => "users/new", :status => :ok, :layout => "signed_out") }
    end
  end
  
  # GET /:username/account/image_status
  def new_image_status
    if current_user.image_status == 'processing'
      render :json => { :job_status => 'processing' },
             :status => :ok
    elsif current_user.image_status == 'success'
      # refresh page to show new image
      if params[:media_type] == 'banner'
        redirect_to user_edit_banner_path(current_user)
      else
        redirect_to user_account_path(current_user)
      end
    elsif current_user.image_status == 'error'
      # we had an issue updating the image
      render :json => { :job_status => 'error' },
             :status => :ok
    else
      # we had an unknown state
      render :json => { :job_status => 'error' },
             :status => :ok
    end
  end
  
  # PUT /:username/account/image
  def new_image
    if params[:filename].blank? || params[:media_type].blank?
      Airbrake.notify(:error_class => "Logged Error", :error_message => "USER IMAGE: Error SAVING image for #{current_user.email}.  REASON: Filename or media_type (image or banner) was blank.") if Rails.env.production?
      render :json => { :error => "There was an error saving your new image.  We have been notified of this issue." }, 
             :status => :unprocessable_entity
    else  
      current_user.update_attribute(:image_status, 'processing')
      new_temp_image = params[:filename]

      if params[:media_type] == 'banner'
        # It's a banner image
        old_banner_image = current_user.read_attribute(:banner_image)

        # Kick off resizing and setting the new image
        # Also pass in the old image and new temp file so we can clean up after ourselves on S3
        current_user.set_new_user_image(old_banner_image, new_temp_image, true)
      elsif params[:media_type] == 'image'
        # It's a profile image
        old_image = current_user.read_attribute(:image)

        # Kick off resizing and setting the new image
        # Also pass in the old image and new temp file so we can clean up after ourselves on S3
        current_user.set_new_user_image(old_image, new_temp_image, false)
      else
        Airbrake.notify(:error_class => "Logged Error", :error_message => "There was a bad media_type passed in (#{params[:media_type]}) when saving a new image for #{current_user.email}.") if Rails.env.production?
        return
      end
      
      # return :ok back to the browser so it can start polling
      # the image status to check when processing is complete
      #
      # we use :start_polling to tell the uploader to only do this
      # for images and not for videos
      render :json => { :start_polling => 'true' }, 
             :status => :ok
    end
  end
  
  # POST /:username/reset_password
  def reset_password
    if params[:password] == params[:password_confirmation]
      # New passwords match so reset it
      @user.update_attributes(:password => params[:password])
      User.should_encrypt_password = true
      if @user.save
        User.should_encrypt_password = false
        sign_in @user
        
        # Clear out the reset token so it can't be reused
        @user.reset_token = ""
        @user.save
        
        redirect_to current_user and return
        
      else
        flash.now[:error] = get_errors_for_class(@user)
        @show_password_reset = true
      end
      User.should_encrypt_password = false
  
    else
      flash.now[:error] = "Passwords do not match.  Please re-enter and confirm your new password."
      @show_password_reset = true
    end
  
    respond_to do |format|
      format.html { render(:template => "users/forgotten_password", :status => :ok, :layout => "signed_out") }
    end
  end
  
  # GET /:username
  # GET /:username.js
  def show
    @browser_title ||= @user.name

    if current_user.blank? || !current_user?(@user)
      # Only show public videos that are complete
      @videos ||= @user.public_videos.paginate(:page => params[:page], :per_page => 10, :order => 'created_at DESC')
    else
      # Show all videos (public and private) except ones that are uploading
      @videos ||= @user.all_videos.paginate(:page => params[:page], :per_page => 10, :order => 'created_at DESC')
    end

    respond_to do |format|
      params[:page].to_i > 1 ? format.js : format.html
    end
  end
  
  # Secondary sign up page for handling errors and showing old fashioned signup form
  # GET /users/signup
  def signup
    @user = User.new
    @invitation ||= InvitationLink.handle_invite_token(params[:invitation_token])
    
    respond_to do |format|
      format.html { render(:template => "users/signup", :status => :ok, :layout => "signed_out") }
    end
  end
  
  # GET /:username/stream
  # GET /:username/stream.js
  def subscriptions_stream
    @browser_title ||= @user.name
    @videos ||= current_user.all_videos_for_subscriptions.paginate(:page => params[:page], :per_page => 10, :order => 'created_at DESC')

    respond_to do |format|
      params[:page].to_i > 1 ? format.js : format.html
    end
  end
  
  # POST /:username/unblock
  def unblock
    blocking = Blocking.where(:requesting_user => current_user.id, :blocked_user => @user.id).first
    if blocking
      if blocking.destroy
        render :nothing => true, :status => :ok
      else
        render :json => { :error => "There was an issue unblocking that person.  We have been notified of this issue." }, 
               :status => :not_found

app/views/users/_featured_videos.html.haml
#featured-videos
  .title
    = image_tag("featured_star.png", :alt => "Featured", :size => "16x16")
    %span 
      - if @user.blank?
        Featured Videos
      - else
        = link_to("Featured Videos", user_channel_path(@user, @user.featured_channel), :class => "white-to-blue")
    - if current_user?(@user)
      %span.edit-order><
        = link_to(user_edit_featured_videos_path(@user)) do
          = image_tag("edit_order.png", :alt => "Edit Order", :size => "13x13")
          %span>< edit order
    
  .videos
    - if @latest_featured_videos.empty?
      %p
        - if @user.blank?
          There aren't any featured videos to show :(
        - else
          #{@user.name} does not have any featured videos to show :(
    - else
      = render :partial => 'shared/featured_video', :collection => @latest_featured_videos

app/views/users/_middle_user_banner.html.haml
.middle-user-banner-container
  = link_to(user_path(@user)) do
    = image_tag("#{ @user.image.blank? ? 'default_user_150px.jpg' : @user.image_url(:large_profile) }", 
          :alt => "#{@user.name}",
          :class => "thumbnail",
          :size => "150x150")

  .user-info-section
    .user-name-and-location
      %span.user-name
        = @user.name
      %span.location
        = @user.location
    %p
      %i
        = @user.bio
    %p.website
      - unless @user.website.blank?
        = link_to(@user.website, "#{@user.website}", :target => "_blank")
    %p
      #{link_to("Videos (#{@user.videos_count})", user_path(@user))} · 
      #{link_to("Channels (#{@user.channels_count})", user_channels_path(@user))} · 
      #{link_to("Badges (#{@user.badges_count})", user_badges_path(@user))} · 
      #{link_to("Subscribers (#{@user.subscribers_count})", user_subscribers_path(@user))} · 
      #{link_to("Subscriptions (#{@user.subscriptions_count})", user_subscriptions_path(@user))}
      
    - if !current_user?(@user)
      %p
        = link_to(user_channels_path(@user), :class => "small subscribe-with-icon btn") do
          = image_tag("add_icon.png", :size => "16x16")
          %span Subscribe
      
.banner-corners
  = image_tag("banner_corners.png", :size => "875x15", :alt => "")

app/views/users/_signup_box.html.haml
/ sign up footer
.landing_signup
  %h3.ras.informationField.signup_box
    Not a member? Sign up and start sharing videos with other people today!
    = link_to "Sign Up", signup_path, :class => "mls ram medium green button"

app/views/users/_signup_form.html.haml
= form_for(@user, :html => { :class => "ptxs"}, :remote => true) do |f|
  .landing_login_form
    %input{:type => "hidden", :name => "uid", :value => @uid}
    %input{:type => "hidden", :name => "provider", :value => @provider}
    %input{:type => "hidden", :name => "oauth_token", :value => @oauth_token}
    %input{:type => "hidden", :name => "oauth_token_secret", :value => @oauth_token_secret}
    %input{:type => "hidden", :name => "social_signup", :value => @social_signup}
    %input{:type => "hidden", :name => "user[location]", :value => @user.location}
    
    - unless @invitation.blank?
      %input{:type => "hidden", :name => "invitation_token", :value => @invitation.token}

    %fieldset.ml25
      = f.label(:username, "Username", :class => "login_label")
      = f.text_field(:username, :autocomplete => :off, :id => "signupUsername", :placeholder => "username", :class => "mls ras toolTipSignup", :title => "", :tabindex => 1, "data-path" => username_availability_path)
      %span.username-availability
        / placeholder
        
    %fieldset.ml25
      = f.label(:name, "Your Name (First & Last)", :class => "login_label")
      = f.text_field(:name, :autocomplete => :off, :id => "signupName", :placeholder => "your name", :class => "mls ras toolTipSignup", :title => "We recommend using your real name so people you know can find you.", :tabindex => 2)
  
    %fieldset.ml25
      = f.label(:email, "E-mail", :class => "login_label")
      = f.text_field(:email, :autocomplete => :off, :id => "signupEmail", :placeholder => "email address", :class => "mls ras toolTipSignup", :title => "We will not share your e-mail address with ANYONE. Period.", :tabindex => 3)
  
    %fieldset.ml25
      = f.label(:password, "Password", :class => "login_label")
      = f.password_field(:password, :autocomplete => :off, :id => "signupPassword", :placeholder => "password", :class => "mls ras toolTipSignup", :title => "Passwords should be longer than 6 characters.", :tabindex => 4)
  
    %fieldset
      = f.label(:birthday, "Date of Birth (age verification only)", :class => "ml30 login_label")
      .dateOfBirth.mlxl
        %select#signupBirthdayMonth.birthday_month.ras{:name => "user[birthday(2i)]", :tabindex => 5}
          %option#signupChooseMonth{:value => ""} Month:
          = options_for_select((1..12).map {|m| [Date::MONTHNAMES[m], m]})
        %select#signupBirthdayDay.birthday_day.ras{:name => "user[birthday(3i)]", :tabindex => 6}
          %option#signupChooseDay{:value => ""} Day:
          = options_for_select((1..31))
        %select#signupBirthdayYear.birthday_year.ras{:name => "user[birthday(1i)]", :tabindex => 7}
          %option#signupChooseYear{:value => ""} Year:
          = options_for_select((1901..Date.today.year).to_a.reverse)
          
    .tcenter
      %fieldset.mtm
        %label{:for => "Agree"}
          %h4.light
            By clicking Sign up, you are indicating that you have read and agree to the
            %a.inlinelink.light{:href => "/tos"}
              terms of service
      
      %fieldset.signupbutton
        = image_tag("ajax_white.gif", :size => "16x16", :class => "soft_hidden signup_ajax_animation")
        %input.ram.green.signup.button{:name => "signup", :type => "submit", :value => "Sign up", :tabindex => 8}
        
- unless @user.birthday.blank?
  - begin
    - parsed_bday = Date.parse @user.birthday.to_s

    :javascript
      $('#signupBirthdayMonth').val(#{parsed_bday.month});
      $('#signupBirthdayDay').val(#{parsed_bday.day});
      $('#signupBirthdayYear').val(#{parsed_bday.year});
  - rescue

app/views/users/_top_banner.html.haml
.top-banner
  - if @user.banner_image_id == 0
    - # The user has uploaded a banner or they are using the default
    = image_tag("#{ @user.banner_image.blank? ? @user.get_banner_image_url(nil) : @user.banner_image_url(:resized) }", :alt => "", :size => "850x315")
  - else
    - # The user has chosen a banner from the gallery
    = image_tag("#{@user.get_banner_image_url(@user.banner_image_id)}", :alt => "", :size => "850x315")
  
  - if current_user?(@user)
    = link_to("Change Banner Image", user_edit_banner_path(current_user), :class => "small primary btn")

app/views/users/_user.html.haml
%li.zebra-striped
  = link_to(user_path(user), :class => "user-image") do
    = image_tag("#{user.image.blank? ? 'default_user_50px.jpg' : user.image_url(:medium_profile) }", 
      :alt => "#{user.name}",
      :size => "50x50")
  
  .user-meta
    %h5
      = link_to(user.name, user_path(user))
    %span #{pluralize(user.videos_count, 'Video')} · #{pluralize(user.badges_count, 'Badge')} · #{pluralize(user.subscribers_count, 'Subscriber')}
    - unless user.bio.blank?
      %p
        %i 
          = auto_link(h(user.bio), :html => { :target => "_blank" })
          
  = link_to("View Channels", user_channels_path(user), :class => "small btn")

app/views/users/create.js.haml
- if @user.errors.any?
  :plain
    $('.formErrorField.js-validate').slideUp("fast", function () { 
      $(this).html('#{escape_javascript(render('shared/error_messages', :klass => @user))}').slideDown('fast'); 
    });

app/views/users/edit_banner.html.haml
- # User Banner Image
= render 'users/top_banner'

- # Middle User Info Section
= render 'users/middle_user_banner'

- # Dark Content Wrapper
.lower-wrapper
  
  - # Main (White) Content Wrapper
  .content-wrapper.standard-padding

    - # Set up the tabs
    %ul.tabs
      %li.active
        %a{:href => "#upload-image"} Upload a Banner
      %li
        %a{:href => "#choose-from-gallery"} Choose one from the Gallery
        
        
    - # Set up the content areas for the tabs
    .pill-content
      #upload-image.active
        .info-message
          %strong Note: 
          Maximum file size of 5 MB.  Please keep it clean and only upload your own images.
          
        #progress-bar
          .progress{:style => "width: 0%;"}
            %span{:style => "display:none;"}
              Uploading
  
        :plain      
          #{s3_uploader('banner')}
        %a{:id => "select-banner", :href => "#", :class => "medium primary btn"} Select Image
        
      #choose-from-gallery
        .info-message
          %strong Note: 
          The images shown below are protected by copyright laws and are made available to Brevidy by Rob Phillips and 
          = succeed "." do
            = link_to "Court Whelan", "http://cwhelanphotography.com", :target => "_blank"
          You may
          %strong
            only
          use them on Brevidy or within screenshots of Brevidy.
        
        .banner-area
          - @banner_images.each do |b|
            = link_to(image_tag("banners/small/#{b.filename}", :size => "250x93"), user_update_banner_from_gallery_path(current_user, :banner_image_id => b.id), :class => "set-new-banner-image thumbnail", :remote => true, :method => :put)

- # Tell the page to scroll down to the content wrapper upon page load
= render 'shared/scroll_to_content_wrapper'

app/views/users/index.html.haml
- # Dark Content Wrapper
.lower-wrapper
  = render 'users/featured_videos'
  
  - # Main (White) Content Wrapper
  .content-wrapper
    = render 'videos/explore_content_titles'

    - if signed_in?
      - # Invitation sell
      - if more_people_can_be_invited?
        .info-message.mhl.centered
          = link_to("Invite your friends and family", user_invitations_path(current_user))
          to join Brevidy and start sharing videos with them today! 

    = cache("find_people_page", :expires_in => 15.minutes) do
      - # Search form
      = form_tag user_search_path, :method => :get, :class => "user-search" do
        = text_field_tag :q, @term, :placeholder => "Search for a name or email"
        %span.search
          %button{:type => "submit", :value => "Go"}

      %ul.user-listing
        = render User.show_random_people

app/views/users/new.html.haml
/ what is brevidy
.pitch_container
  .pitch.left
    .pitch_img.left
      = image_tag("fleeting_moments.png", :size => "175x88")
    %ul.right.mts.mll
      %li
        %h1 Share the fleeting moments of your life on video
      %li.mlm.mtm
        %h2 
          Upload videos from your computer or share them from YouTube or Vimeo!
          .mtm
            Make videos public for the world to see, or make them private to share only with your family and friends.
            The choice is yours.
  
  .pitch.left.mtl
    .pitch_img.left
      = image_tag("connect_people.png", :size => "96x125", :class => "connect_people")
    %ul.right.mll.connect_people
      %li
        %h1 Connect with people around you
      %li.mlm.mtm
        %h2 
          Subscribe to channels that interest you! Give people badges to express exactly how you feel about their videos!
          Share other people's videos that you find interesting!
          
  .pitch.left.mtl
    .pitch_img.left
      = image_tag("social_sharing.png", :size => "129x115", :class => "social_sharing")
    %ul.right.mll.social_sharing
      %li
        %h1 Let others join in the fun
      %li.mlm.mtm
        %h2 
          Easily share any video to your social networks! Send your family and friends a link so they can
          watch your private videos without signing up!
  
  .signup.left
    .social_buttons
      = link_to(image_tag("social_signup_facebook.png", :size => "225x43", :class => "left"), "#{root_url}auth/facebook")
      = link_to(image_tag("social_signup_twitter.png", :size => "225x43", :class => "right"), "#{root_url}auth/twitter")
      
  .old_fashioned.left.tcenter
    = link_to("...or sign up the old fashioned way", signup_path)

app/views/users/show.js.haml
= render @videos

app/views/users/subscriptions_stream.html.haml
- # User Banner Image
= render 'users/top_banner'

- # Middle User Info Section
= render 'users/middle_user_banner'

- # Dark Content Wrapper
.lower-wrapper
  = render 'users/featured_videos'
  
  - # Main (White) Content Wrapper
  .content-wrapper
    = render 'shared/content_titles'
  
    - if @videos.blank?
      .info-message.mhl
        There are no videos in your stream to show.
    - else
      = render @videos
    
    = will_paginate @videos
  
    = render :partial => "shared/infinite_scrolling", :locals => { :item_selector => ".video-post" }

app/views/users/subscriptions_stream.js.haml
= render @videos