config/routes.rb
Brevidy::Application.routes.draw do
  # Domain Route
  root :to => 'users#new'
  
  # Session / Authentication Routes
  resources :sessions, :only => [:create]
  match :login, :to => 'sessions#new'
  match :logout, :to => 'sessions#destroy'
  match :signup, :to => 'users#signup'
  match "/auth/:provider/callback", :to => "sessions#create_social_session"
  match "/auth/failure", :to => "errors#error_social_auth"
  match "/auth/deauthorize", :to => "social_networks#deauthorize"
  match 'account/forgotten_password', :to => 'users#forgotten_password', :as => :forgotten_password, :via => [:get]
  match 'account/validate_forgotten_password', :to => 'users#validate_forgotten_password', :as => :validate_forgotten_password, :via => [:post]
  
  # Explore Routes
  match :explore, :to => 'videos#explore', :via => [:get] # aka the popular videos page
  #match 'explore/suggested_channels', :to => 'videos#suggested_channels', :as => :suggested_channels, :via => [:get]
  #match 'explore/recent', :to => 'videos#recent', :as => :recent_videos, :via => [:get]
  match 'explore/users', :to => 'users#index', :as => :find_people, :via => [:get]
  
  # Invitation Route
  match 'invitations/:invitation_token', :to => 'users#new', :as => :signup_via_invitation, :via => [:get]
  
  # Search Routes
  match 'search/videos', :to => 'search#videos', :as => :video_search, :via => [:get]
  match 'search/users', :to => 'search#users', :as => :user_search, :via => [:get]
  
  # Public Video / Channel Routes
  match 'p/:public_token', :to => 'public_videos#show', :as => :public_video, :via => [:get]
  match 'embed/:public_token', :to => 'public_videos#embed', :as => :embed_video, :via => [:get]
  match 'c/:public_token', :to => 'channels#show_by_token_access', :as => :public_channel, :via => [:get]
  
  # People You May Know Route
  # match 'users/people_you_may_know', :to => 'users#people_you_may_know', :as => :people_you_may_know, :via => [:get]

  # Public Page Routes such as Contact, Privacy, etc
  match 'help/faq', :to => 'public#faq', :via => [:get], :as => :faq
  match 'help/video_faq', :to => 'public#video_faq', :via => [:get], :as => :video_faq
  match 'help/video_guidelines', :to => 'public#video_guidelines', :via => [:get], :as => :video_guidelines 
  match 'help/contact', :to => 'public#contact', :via => [:get], :as => :contact
  match 'help/privacy', :to => 'public#privacy', :via => [:get], :as => :privacy
  match 'help/tos', :to => 'public#tos', :via => [:get], :as => :tos

  # Users Create
  resources :users, :only => [:create]
  
  # Username Availability
  match :username_availability, :to => 'users#username_availability', :via => [:get]
  
  # This needs to go at the bottom of this routes.rb file to catch 
  # all routes that didn't match the routes specified above.
  #
  ## This regex constraint handles these cases: http://rubular.com/r/PiP1nTNph2
  ### alphanumeric with underscores only; can't have consecutive underscores; can't be only an underscore;
  ### can be only a letter; can't start with a number or be only a number; can't contain spaces; can end in an underscore;
  ### can't be only an underscore and numbers (if it starts with an underscore, the next char must be a letter)
  controller :users, :path => '/:username', :as => :user, :constraints => { :username => /_?[a-z]_?(?:[a-z0-9]_?)*/i } do
    resources :badges, :only => [:index]
    resources :channels do
      match :request_access, :to => 'subscriptions#handle_access_request', :via => [:get]
      match :subscribe, :to => 'subscriptions#create', :via => [:post]
      match :unsubscribe, :to => 'subscriptions#destroy', :via => [:delete]
      match :remove_subscriber, :to => 'subscriptions#remove_subscriber', :via => [:delete]
    end
    match :about, :to => 'profile#index', :via => [:get]
    match 'about/update/:id', :to => 'profile#update', :as => :update_about, :via => [:put]
    resources :videos, :except => [:create, :index] do
      resources :badges, :only => [:create, :destroy]
      match 'badges', :to => 'badges#badges_dialog', :as => :badges_dialog, :via => [:get]
      resources :comments, :only => [:create, :destroy]  
      get :embed_code
      match :flag, :to => 'videos#flag', :via => [:post]
      match '/flag/dialog', :to => 'videos#flag_video_dialog', :as => :flag_dialog, :via => [:get]
      match :share_via_email, :to => 'videos#share_via_email'
      resources :tags, :only => [:destroy]
      
      # uploading routes
      post :encoder_callback
      put :successful_upload
      put :upload_error    
    end
    resources :social_networks, :only => [:destroy]
    
    # All matched routes that are nested under User go here
    match '/', :to => 'users#show', :via => [:get]
    match :edit_banner, :to => 'users#edit_banner', :via => [:get]
    match :invite_people, :to => 'invitation_link#create'
    match :invitations, :to => 'invitation_link#index'
    match :latest_activity, :to => 'user_events#show', :via => [:get]
    match 'add_to_channel/dialog', :to => 'videos#add_to_channel_dialog', :as => :add_to_channel_dialog, :via => [:get]
    match 'add_to_channel', :to => 'videos#add_to_channel', :as => :add_to_channel, :via => [:post]
    match 'share/dialog', :to => 'videos#share_dialog', :as => :share_dialog, :via => [:get]
    match 'share', :to => 'videos#share', :as => :create_shared_video, :via => [:post]
    match :edit_featured_videos, :to => 'channels#edit_featured_videos', :via => [:get]
    match :update_featured_videos, :to => 'channels#update_featured_videos', :via => [:put]
    match 'stream', :to => 'users#subscriptions_stream'
    match :account, :to => 'users#edit'
    match 'account/update', :to => 'users#update', :via => [:put]
    match 'account/image', :to => 'users#new_image', :via => [:put]
    match 'account/image_status', :to => 'users#new_image_status', :via => [:get]
    match :update_banner_from_gallery, :to => 'users#update_banner_from_gallery', :via => [:put]
    match :update_background_image, :to => 'users#update_background_image', :via => [:put]
    match 'account/password', :to => 'users#update_password', :via => [:put]
    match 'account/birthday', :to => 'users#update_birthday', :via => [:put]
    match 'account/notifications', :to => 'users#update_notifications', :via => [:put]
    match :subscriptions, :to => 'subscriptions#subscriptions'
    match :subscribers, :to => 'subscriptions#subscribers'
    match :block, :to => 'users#block'
    match :unblock, :to => 'users#unblock'
    match :validate_reset_password, :to => 'users#validate_reset_password', :via => [:get]
    match :reset_password, :to => 'users#reset_password', :via => [:post]
  end

  # Catches all bad routes that weren't matched with the above routes and shows 404 page instead
  match '*a', :to => 'errors#routing'
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  include ApplicationHelper

  skip_before_filter :http_authenticate, :verify_authenticity_token, :only => [:encoder_callback]
  skip_before_filter :site_authenticate, :only => [:embed_code, :encoder_callback, :explore, :flag, :flag_video_dialog, :share_via_email, :show]
  before_filter :set_user, :except => [:explore]
  before_filter :verify_current_user_is_not_blocked, :only => [:add_to_channel, :add_to_channel_dialog, :flag, :flag_video_dialog]
  before_filter :set_video_based_on_user, :only => [:destroy, :edit, :embed_code, :flag, :flag_video_dialog, :share_via_email, :show]
  before_filter :verify_user_can_access_channel, :only => [:share_via_email, :show]
  before_filter :verify_user_can_access_channel_or_video, :only => [:embed_code]
  before_filter :verify_user_owns_video, :only => [:destroy, :edit]
  before_filter :set_featured_videos, :only => [:show]
  
  respond_to :js, :only => [:add_to_channel_dialog]
  
  # POST /:username/add_to_channel
  # Access control is handled in the "add_video_to_channel!" method
  def add_to_channel    
    new_shared_video ||= Video.add_video_to_channel!(current_user, 
                                                     params[:video_id],
                                                     params[:channel_id], 
                                                     params[:channel_name],
                                                     params[:channel_is_private])
  
    if new_shared_video.errors.any?
      render :json => { :error => get_errors_for_class(new_shared_video).to_sentence },
             :status => :unprocessable_entity
    else
      render :nothing => true, :status => :created
    end
  end
  
  # GET /:username/add_to_channel/dialog
  # Access control is handled within this method
  def add_to_channel_dialog
    @video ||= Video.where(:id => params[:video_id]).joins(:video_graph).where(:video_graphs => { :status => VideoGraph.get_status_number(:ready) }).first
    render :json => { :error => "That video could not be found." }, :status => :not_found and return if @video.blank?
  
    if @video.channel.private? && !current_user_owns?(@video)
      render :json => { :error => "This video is in a private channel so it cannot be shared." }, 
             :status => :unprocessable_entity
    else    
      @user ||= get_object_owner(@video)
      if user_can_access_channel         
        respond_with(@user, @video)
      else
        render :json => { :error => "You do not have permission to share this video." },
               :status => :unauthorized
      end
    end
  end
  
  # DELETE /:username/videos/:id
  def destroy  
    if @video.destroy
      render :nothing => true, :status => :ok
    else
      render :json => { :error => get_errors_for_class(@video).to_sentence }, 
             :status => :unprocessable_entity
    end
  end
  
  # GET /:username/videos/:id/edit
  def edit
    @browser_title ||= "Edit Video"
  end
  
  # GET /:username/videos/:video_id/embed_code
  def embed_code
    render :json => { :html => render_to_string( :partial => 'videos/embed_code.html',
                                                 :locals => { :video => @video } )  
                    },
           :status => :ok

    # Create an entry for a video being played
    UserEvent.create(:event_type => UserEvent.event_type_value(:video_play), 
                     :event_object_id => @video.id,
                     :user_id => @video.user_id,
                     :event_creator_id => current_user.blank? ? 0 : current_user.id)
  end
  
  # POST /:username/videos/:id/encoder_callback
  def encoder_callback    
    @video = @user.videos.find_by_id(params[:video_id])
    if @video
      # Check for expected JSON params in callback.
      if !(params[:output].blank? or params[:output][:state].blank?)
        job_state = params[:output][:state]

        # Check that video was in the expected state.
        if @video.is_status?(VideoGraph::TRANSCODING)

          if job_state.downcase == "finished"
            # Transcoding was successful
            vg = @video.video_graph
            vg.set_status(VideoGraph::READY)
            vg.save

            # set the created_at time to right now so it shows
            # at the top of the stream
            @video.created_at = Time.now
            @video.save
        
            # send the video to their social networks
            video_owner = User.find_by_id(@video.user_id)
            facebook_connected = SocialNetwork.find_by_user_id_and_provider(video_owner.id, "facebook") 
            twitter_connected = SocialNetwork.find_by_user_id_and_provider(video_owner.id, "twitter")
            @video.send_to_facebook_or_twitter("facebook", facebook_connected) if (@video.send_to_facebook? && facebook_connected)
            @video.send_to_facebook_or_twitter("twitter", twitter_connected) if (@video.send_to_twitter? && twitter_connected)
      
            UserMailer.delay.video_is_done_encoding(video_owner, @video) if video_owner.send_email_for_encoding_completion
          else
            # Transcoding had an error
            # Handle the transcoding error by either retrying
            # the job or treating it as a fatal error
            @video.video_graph.handle_transcoding_error(params)
          end

          render :text => "Video encoding status received.",
                 :status => :ok
        else
          # Don't modify the state, tell Zencoder we got this, and log an error so we can investigate
          render :text => "Error: Video in unexpected state.",
                 :status => :ok
          Airbrake.notify(:error_class => "Logged Error", :error_message => "ERROR: Callback received on file in incorrect state. Expected state: Transcoding. State: #{@video.status}") if Rails.env.production?
        end
      else
        # Don't modify the state and return a malformed request error to Zencoder
        render :text => "Error: Malformed callback.",
               :status => :bad_request
        Airbrake.notify(:error_class => "Logged Error", :error_message => "ERROR: Callback received with malformed parameters.  Params: #{params}") if Rails.env.production?
      end
    else
      render :text => "Error: Video not found (it might have been deleted).",
             :status => :not_found
    end
=begin
    # Sample success response from zencoder
    
    {"output"=>{"state"=>"finished", "url"=>"http://brevidytest.s3.amazonaws.com/uploads/videos/101/111/enc1_f64d1d9f26314cb.mp4", "label"=>"f64d1d9f26314cb", "id"=>5264824},
    "job"=>{"test"=>true, "state"=>"finished", "id"=>4955170},
    "action"=>"encoder_callback",
    "controller"=>"videos",
    "user_id"=>"101",
    "id"=>"111"}
=end
  end
  
  # GET /explore
  def explore
    # show the 4 latest featured videos
    #@latest_featured_videos = User.find_by_username("brevidy").featured_videos.limit(4)
    
    @latest_featured_videos = []
    
    # only show most recent public videos that have a :ready state
    @videos ||= Video.joins(:channel).where(:channels => { :private => false }).joins(:video_graph).where(:video_graphs => { :status => VideoGraph.get_status_number(:ready) }).
                      paginate(:page => params[:page], :per_page => 10, :order => 'created_at DESC')
  
    respond_to do |format|
      params[:page].to_i > 1 ? format.js : format.html
    end
  end
  
  # POST /:username/videos/:video_id/flag
  def flag
    flag_id = params[:flag_id]
    detailed_reason = params[:detailed_reason]

    if flag_id && Flag.where(:id => flag_id).exists?
      
      if signed_in?      
        # Check if the currently signed in user has already flagged this video for this reason
        if VideoFlag.where(:flagged_by => current_user.id, :video_id => @video.id, :flag_id => flag_id).exists?
          render :json => { :error => "You have already flagged this video for this reason.  Thank you for your patience while we look into the issue for you." }, 
                 :status => :unprocessable_entity and return
        end
      else
        # Check if a cookie exists that says they have already flagged this video for this reason
        unless session[:flagged_video].blank?
          if session[:flagged_video][:video_id] == @video.id && session[:flagged_video][:flag_id] == flag_id
            render :json => { :error => "You have already flagged this video for this reason.  Thank you for your patience while we look into the issue for you." }, 
                   :status => :unprocessable_entity and return
          end
        end
      end
      
      # Video has not been flagged by the current user or the signed out user, so let's flag it
      new_flagging = VideoFlag.new(:flag_id => flag_id, 
                                   :detailed_reason => detailed_reason)
      new_flagging.video_id = @video.id
      new_flagging.flagged_by = signed_in? ? current_user.id : nil                            
      if new_flagging.save
        render :nothing => true,
               :status => :created
      
        # Send an email to support@brevidy.com
        UserMailer.delay(:priority => 40).flagged_video(new_flagging, current_user)
        
        # Save a cookie about this event
        session[:flagged_video] = { :video_id => @video.id, :flag_id => flag_id }
      else
        render :json => { :error => get_errors_for_class(new_flagging).to_sentence }, 
               :status => :unprocessable_entity
        Airbrake.notify(:error_class => "Logged Error", :error_message => "FLAGGING: We were unable to flag a video for User (#{current_user.email unless current_user.blank?}), Video (#{video_id}), Flag Type (#{flag_id}), and Detailed Reason #{detailed_reason})") if Rails.env.production?
      end

    else
      render :json => { :error => "You must select one of the given options for why you want to flag the video!" }, 
           :status => :unprocessable_entity
    end
  end
  

app/views/videos/_add_to_channel_dialog.html.haml
#brevidy-modal.modal.hide
  = form_tag(user_add_to_channel_path(current_user), :id => "add-to-channel-form", :method => "POST", :remote => true) do
    .modal-header
      %h3 Add this video to one of your channels
    .modal-body
      - if current_user_owns?(video)
        .add-to-channel-warning
          .p
            %strong Note:
            You are about to create a copy of a video you already posted.  Did you want to 
            = link_to("organize this video into a different channel", edit_user_video_path(current_user, video)) 
            instead?
          .p.mtxl
            = link_to("Click here if you still want to create a copy of this video", "#", :class => "show-add-video-meta-area")
          
      .add-video-meta-area{:style => current_user_owns?(video) ? "display:none" : ""}
        .video-preview-area
          %input{:name => "video_id", :value => video.id, :type => "hidden"}
          = image_tag(video.get_thumbnail_url(video.selected_thumbnail), :alt => video.title, :size => "100x54")
          %p.title
            %strong #{video.title}
          %p.description #{truncate(video.description, :length => 100, :omission => '...')}
        
        .channel-selection-area
          %p 
            %strong Which channel should it go in?
          = render 'videos/channel_options'
        
    .modal-footer
      .ajax-errors
        - # placeholder for ajax errors to be shown
      
      = submit_tag("Add to Channel", :id => "add-to-channel", :class => "modal-confirm-btn btn primary", :style => current_user_owns?(video) ? "display:none" : "")
      %a.modal-cancel-btn.btn.secondary{:href => "#"} Cancel
      = image_tag("ajax.gif", :class=>"ajax-animation", :size => "16x16")

app/views/videos/_video.html.haml
- # Initialize some objects for each video
- # such as badges, comments, tags, etc.
- video_owner ||= get_object_owner(video)
- comments ||= video.comments
- tags ||= video.tags
- badges_count ||= video.badges.count
- unique_badge_types_and_counts ||= video.unique_badge_types_and_counts

- # checks that the video isn't processing so we will
- # allow the user to interact with it (play it, badge it, etc.)
- video_is_clickable ||= video.is_status?(VideoGraph::READY)

- # checks whether we should expand the video or not
- expand_the_video = defined?(expand_video) ? expand_video : false

- # Checks if the video is a YouTube/Vimeo player
- video_is_not_remote ||= video.remote_video_id.blank?

.video-post{"data-video-id"=>"#{video.id}"}
  .row.heading
    = link_to(user_path(video_owner)) do
      = image_tag("#{video_owner.image.blank? ? 'default_user_50px.jpg' : video_owner.image_url(:medium_profile) }", :alt => "#{video_owner.name}", :size => "50x50")
    .video-title-and-info
      %h3
        = video.title
      %p
        Shared by 
        = link_to(video_owner.name, user_path(video_owner))
        into their
        = link_to(video.channel.title, user_channel_path(video_owner, video.channel))
        channel 
        %span.gray
          - begin
            - if video_is_not_remote
              - via_user = video.video_graph.get_user_who_uploaded_this
              - unless via_user.blank? || (video_owner.id == via_user.id)
                (via #{link_to(via_user.name, user_path(via_user))})
          - rescue

          #{time_ago_in_words(video.created_at)} ago
  
    - # Settings drop down menu
    %ul.settings-menu
      %li.dropdown{"data-dropdown" => "dropdown"}
        %a.settings-icon.dropdown-toggle.prevent-jump{:href => "#"}
          %i
        %ul.dropdown-menu
          %li
            = link_to("Flag Video", user_video_flag_dialog_path(video_owner, video), :remote => true, "data-method" => "GET")
          - if current_user_owns?(video)
            %li
              = link_to("Edit Video", edit_user_video_path(video_owner, video))
            %li
              = link_to("Delete Video", user_video_path(video_owner, video), :class => "delete-video", "data-video-id" => "#{video.id}")
  
  .row.video-meta
    .player-area{"data-video-id"=>"#{video.id}", :style => expand_the_video ? "display:block" : ""}
      .collapse-player-controls
        %a.pull-right{:href => "#", "data-video-id" => "#{video.id}"} Close video
        
      .player-object{:id => "brevidy-player-#{video.id}"}
        - if expand_the_video
          = render :partial => 'videos/embed_code', :locals => { :video => video, :individual_player => true }
        - else
          - # Player code will be AJAX'ed in here
    
    .thumbnail-and-badges
      %a{:href => "#"}
        - path_to_this = @viewing_via_token_access ? user_video_embed_code_path(video_owner, video, :channel_token => video.channel.public_token) : user_video_embed_code_path(video_owner, video)
        .thumbnail{:class => video_is_clickable ? "" : "processing", "data-video-id"=>"#{video.id}", "data-video-path" => video_is_clickable ? "#{path_to_this}" : "", :style => expand_the_video ? "display:none" : ""}
          = image_tag(video_is_clickable ? video.get_thumbnail_url(video.selected_thumbnail) : "processing.png", :alt => video.title, :size => "250x134")
          - if video_is_clickable
            %i.play-icon
              = image_tag("play.png", :alt => "Play", :size => "60x45")
        
      - if video_is_clickable
        .show-badges{"data-video-id"=>"#{video.id}"}
          - if badges_count == 0
            %p.no-badges-given-yet{:class => (badges_count != 0) ? "mtm" : ""}
              No badges given yet.
              
              - if signed_in?
                %a.give-first-badge{:href=>"#", "data-video-id"=>"#{video.id}"} Give one!
          - else
            .badges
              %ul
                - unique_badge_types_and_counts[:badge_sets].first(5).each do |icon, count|
                  = render :partial => "badges/badge", :locals => { :icon => icon, :count => count }
                  
            %p.view-all-badges{"data-video-id"=>"#{video.id}"}
              = render :partial => "badges/view_all_badges.html", 
                       :locals => { :badges_count => badges_count, :video_owner => video_owner, :video => video }
            
    .description-and-controls
      .description.expandable
        - if video.description.blank?
          %i No description given for this video
        - else
          = simple_format(auto_link(h(video.description), :html => { :target => "_blank" }), {}, :sanitize => false)
      
      - if video_is_clickable    
        .controls
          %ul
            - if current_user_owns?(video) || !video.channel.private?
              %li.video-control-link
                - if current_user.blank?
                  = link_to(login_path, :class => "show-msg-modal", "data-modal-title" => "Please login or sign up", "data-modal-message" => "You must <a href='#{login_path}'>Login</a> or <a href='#{signup_path}'>Sign up</a> before you can add a video to a channel.") do
                    = image_tag("add_to_channel.png", :alt => "Channel Icon", :size => "13x13", :class => "control-icon")
                    %span>< Add To Channel
                - else
                  = link_to(user_add_to_channel_dialog_path(current_user, :video_id => video.id), :class => "add-to-channel-link", "data-video-id" => "#{video.id}", :remote => true, "data-method" => "GET") do
                    = image_tag("add_to_channel.png", :alt => "Channel Icon", :size => "13x13", :class => "control-icon")
                    %span>< Add To Channel
          
            %li.video-control-link
              %a.badge-link{:href => "#", "data-video-id" => "#{video.id}"}
                = image_tag("badge_it.png", :alt => "Badge Icon", :size => "13x13", :class => "control-icon")
                %span>< Badge It
              %span.badge-arrow{"data-video-id" => "#{video.id}"}
            
            %li.video-control-link
              %a.comment-link{:href => "#", "data-video-id" => "#{video.id}"}
                = image_tag("comment.png", :alt => "Comment Icon", :size => "13x13", :class => "control-icon")
                %span>< Comment
              %span.comment-arrow{"data-video-id" => "#{video.id}", :style => comments.blank? ? "display: none" : ""}
            
            - if current_user_owns?(video) || !video.channel.private?
              %li.video-control-link
                %a.share-link{:href => "#", "data-video-id" => "#{video.id}"}
                  = image_tag("share.png", :alt => "Share Icon", :size => "13x13", :class => "control-icon")
                  %span>< Share
                %span.share-arrow{"data-video-id" => "#{video.id}"}
            
            %li.video-control-link
              %a.tag-link{:href => "#", "data-video-id" => "#{video.id}"}
                = image_tag("tags.png", :alt => "Tags Icon", :size => "13x13", :class => "control-icon")
                %span>< Tags
              %span.tag-arrow{"data-video-id" => "#{video.id}"}
            
            %li.ajax-animation{"data-video-id" => "#{video.id}"}
              = image_tag("ajax.gif", :size => "16x16")
        
        - # -----------
        - # BADGES AREA
        - # -----------
        .badges-area{"data-video-id" => "#{video.id}"}
          - # Render all of the active badges to choose from
          = render :partial => "badges/give_badges.html", :collection => get_all_active_badges, 
                   :locals => { :video => video, 
                                :video_owner => video_owner, 
                                :all_badge_types => unique_badge_types_and_counts[:all_badge_types] }
      
        - # -------------
        - # COMMENTS AREA
        - # -------------
        .comments-area{"data-video-id" => "#{video.id}", :style => comments.blank? ? "display: none" : ""}
          - if current_user.blank? && comments.blank?
            %p.no-content-msg
              %i No one has commented on this video yet.
            
          - else
            %ul.comments-list
              - if comments.size > 3
                %li.show-all-comments 
                  %a.show-all-comments{:href => "#", "data-video-id" => "#{video.id}"}
                    Show all #{comments.size} comments
              
                - # Hide everything except the latest 3 comments
                = render :partial => "comments/comment.html", 
                  :collection => comments[-comments.size..-4], 
                  :locals => { :video => video, :video_owner => video_owner, :hidden_comment => true }
              
                - # Show only the latest 3 comments in ASC order 
                = render :partial => "comments/comment.html", :collection => comments[-3..-1], 
                  :locals => { :video => video, :video_owner => video_owner, :hidden_comment => false }
                
              - else
                = render :partial => "comments/comment.html", :collection => comments, 
                  :locals => { :video => video, :video_owner => video_owner, :hidden_comment => false }
                
          - unless current_user.blank?
            .comment-box
              .comment-form-wrapper
                = form_tag(user_video_comments_path(video_owner, video), :method => "POST", :remote => true, :class => "post-new-comment", "data-video-id" => "#{video.id}") do
                  - if @viewing_via_token_access
                    %input{:name => "channel_token", :type => "hidden", :value => "#{video.channel.public_token}"}/
                  
                  = text_area_tag(:content, nil, :autocomplete => :off, "data-video-id" => "#{video.id}", :placeholder => "Write a comment")
                  .button-wrapper{"data-video-id" => "#{video.id}"}
                    %input.btn.primary.small{:type => "submit", :value => "Comment", "data-video-id" => "#{video.id}"}
      
        - # ----------
        - # SHARE AREA
        - # ----------
        - if current_user_owns?(video) || !video.channel.private?
          .share-area{"data-video-id" => "#{video.id}"}
            .share-content
              - # the user owns the video or the channel holding the video is public
              #{link_to("Social sharing", "#", :class => "share-socially lighten-to-blue")} · #{link_to("Link to this video", "#", :class => "link-to-video")} · #{link_to("Embed this video", "#", :class => "embed-video")} · #{link_to("Email this video", "#", :class => "email-video")}
              
              - public_url_to_this_video = public_video_url(:public_token => video.public_token)
              .social-sharing
                / AddThis Button BEGIN
                .addthis_toolbox.addthis_default_style.addthis_32x32_style{"addthis:url" => public_url_to_this_video, "addthis:title" => "Check out this video! '#{truncate(video.title, :length => 70, :omission => '...')}'" }
                  %a.addthis_button_facebook
                  %a.addthis_button_twitter
                  %a.addthis_button_stumbleupon
                  %a.addthis_button_reddit
                  %a.addthis_button_digg
                  %a.addthis_button_gmail
                  %a.addthis_button_compact
                / AddThis Button END
              
              .public-link
                %input{:type => "text", :readonly => true, :value => public_url_to_this_video}
          
              .embed-code
                %textarea{:readonly => true}
                  :plain
                    <iframe src="#{embed_video_url(:public_token => video.public_token)}" width="560" height="310" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
              
              .email-form
                = form_tag(user_video_share_via_email_path(video_owner, video), :class => "share-via-email", :remote => true, :method => "POST") do
                  %label{:for => "recipient_email"} Email Address
                  %input{:name => "recipient_email", :type => "text", :placeholder => "email address"}
                  %label{:for => "personal_message"} Personal Message (optional)
                  %textarea{:name => "personal_message", :placeholder => "Personalize your email!"}
                  %input.btn.primary.small{:type => "submit", :value => "Send"}
                
          
        - # ---------
        - # TAGS AREA
        - # ---------
        .tags-area{"data-video-id" => "#{video.id}"}
          - if tags.blank?
            %p.no-content-msg
              %i
                There are currently no tags organizing this video.
                - if current_user_owns?(video)
                  = link_to("Give it some", edit_user_video_path(video_owner, video))
        
          - else
            %ul
              - tags.each do |t|
                %li
                  = link_to(t.content, video_search_path(:tag => t.content))
                  - if current_user_owns?(video)
                    = link_to("x", user_video_tag_path(video_owner, video, t), :class => "tooltip remove-tag",
                      :method => "DELETE", :remote => true, :title => "Remove tag", "data-video-id" => "#{video.id}")