config/routes.rb
Brevidy::Application.routes.draw do
  # Domain Route
  root :to => 'users#new'
  
  # Session / Authentication Routes
  resources :sessions, :only => [:create]
  match :login, :to => 'sessions#new'
  match :logout, :to => 'sessions#destroy'
  match :signup, :to => 'users#signup'
  match "/auth/:provider/callback", :to => "sessions#create_social_session"
  match "/auth/failure", :to => "errors#error_social_auth"
  match "/auth/deauthorize", :to => "social_networks#deauthorize"
  match 'account/forgotten_password', :to => 'users#forgotten_password', :as => :forgotten_password, :via => [:get]
  match 'account/validate_forgotten_password', :to => 'users#validate_forgotten_password', :as => :validate_forgotten_password, :via => [:post]
  
  # Explore Routes
  match :explore, :to => 'videos#explore', :via => [:get] # aka the popular videos page
  #match 'explore/suggested_channels', :to => 'videos#suggested_channels', :as => :suggested_channels, :via => [:get]
  #match 'explore/recent', :to => 'videos#recent', :as => :recent_videos, :via => [:get]
  match 'explore/users', :to => 'users#index', :as => :find_people, :via => [:get]
  
  # Invitation Route
  match 'invitations/:invitation_token', :to => 'users#new', :as => :signup_via_invitation, :via => [:get]
  
  # Search Routes
  match 'search/videos', :to => 'search#videos', :as => :video_search, :via => [:get]
  match 'search/users', :to => 'search#users', :as => :user_search, :via => [:get]
  
  # Public Video / Channel Routes
  match 'p/:public_token', :to => 'public_videos#show', :as => :public_video, :via => [:get]
  match 'embed/:public_token', :to => 'public_videos#embed', :as => :embed_video, :via => [:get]
  match 'c/:public_token', :to => 'channels#show_by_token_access', :as => :public_channel, :via => [:get]
  
  # People You May Know Route
  # match 'users/people_you_may_know', :to => 'users#people_you_may_know', :as => :people_you_may_know, :via => [:get]

  # Public Page Routes such as Contact, Privacy, etc
  match 'help/faq', :to => 'public#faq', :via => [:get], :as => :faq
  match 'help/video_faq', :to => 'public#video_faq', :via => [:get], :as => :video_faq
  match 'help/video_guidelines', :to => 'public#video_guidelines', :via => [:get], :as => :video_guidelines 
  match 'help/contact', :to => 'public#contact', :via => [:get], :as => :contact
  match 'help/privacy', :to => 'public#privacy', :via => [:get], :as => :privacy
  match 'help/tos', :to => 'public#tos', :via => [:get], :as => :tos

  # Users Create
  resources :users, :only => [:create]
  
  # Username Availability
  match :username_availability, :to => 'users#username_availability', :via => [:get]
  
  # This needs to go at the bottom of this routes.rb file to catch 
  # all routes that didn't match the routes specified above.
  #
  ## This regex constraint handles these cases: http://rubular.com/r/PiP1nTNph2
  ### alphanumeric with underscores only; can't have consecutive underscores; can't be only an underscore;
  ### can be only a letter; can't start with a number or be only a number; can't contain spaces; can end in an underscore;
  ### can't be only an underscore and numbers (if it starts with an underscore, the next char must be a letter)
  controller :users, :path => '/:username', :as => :user, :constraints => { :username => /_?[a-z]_?(?:[a-z0-9]_?)*/i } do
    resources :badges, :only => [:index]
    resources :channels do
      match :request_access, :to => 'subscriptions#handle_access_request', :via => [:get]
      match :subscribe, :to => 'subscriptions#create', :via => [:post]
      match :unsubscribe, :to => 'subscriptions#destroy', :via => [:delete]
      match :remove_subscriber, :to => 'subscriptions#remove_subscriber', :via => [:delete]
    end
    match :about, :to => 'profile#index', :via => [:get]
    match 'about/update/:id', :to => 'profile#update', :as => :update_about, :via => [:put]
    resources :videos, :except => [:create, :index] do
      resources :badges, :only => [:create, :destroy]
      match 'badges', :to => 'badges#badges_dialog', :as => :badges_dialog, :via => [:get]
      resources :comments, :only => [:create, :destroy]  
      get :embed_code
      match :flag, :to => 'videos#flag', :via => [:post]
      match '/flag/dialog', :to => 'videos#flag_video_dialog', :as => :flag_dialog, :via => [:get]
      match :share_via_email, :to => 'videos#share_via_email'
      resources :tags, :only => [:destroy]
      
      # uploading routes
      post :encoder_callback
      put :successful_upload
      put :upload_error    
    end
    resources :social_networks, :only => [:destroy]
    
    # All matched routes that are nested under User go here
    match '/', :to => 'users#show', :via => [:get]
    match :edit_banner, :to => 'users#edit_banner', :via => [:get]
    match :invite_people, :to => 'invitation_link#create'
    match :invitations, :to => 'invitation_link#index'
    match :latest_activity, :to => 'user_events#show', :via => [:get]
    match 'add_to_channel/dialog', :to => 'videos#add_to_channel_dialog', :as => :add_to_channel_dialog, :via => [:get]
    match 'add_to_channel', :to => 'videos#add_to_channel', :as => :add_to_channel, :via => [:post]
    match 'share/dialog', :to => 'videos#share_dialog', :as => :share_dialog, :via => [:get]
    match 'share', :to => 'videos#share', :as => :create_shared_video, :via => [:post]
    match :edit_featured_videos, :to => 'channels#edit_featured_videos', :via => [:get]
    match :update_featured_videos, :to => 'channels#update_featured_videos', :via => [:put]
    match 'stream', :to => 'users#subscriptions_stream'
    match :account, :to => 'users#edit'
    match 'account/update', :to => 'users#update', :via => [:put]
    match 'account/image', :to => 'users#new_image', :via => [:put]
    match 'account/image_status', :to => 'users#new_image_status', :via => [:get]
    match :update_banner_from_gallery, :to => 'users#update_banner_from_gallery', :via => [:put]
    match :update_background_image, :to => 'users#update_background_image', :via => [:put]
    match 'account/password', :to => 'users#update_password', :via => [:put]
    match 'account/birthday', :to => 'users#update_birthday', :via => [:put]
    match 'account/notifications', :to => 'users#update_notifications', :via => [:put]
    match :subscriptions, :to => 'subscriptions#subscriptions'
    match :subscribers, :to => 'subscriptions#subscribers'
    match :block, :to => 'users#block'
    match :unblock, :to => 'users#unblock'
    match :validate_reset_password, :to => 'users#validate_reset_password', :via => [:get]
    match :reset_password, :to => 'users#reset_password', :via => [:post]
  end

  # Catches all bad routes that weren't matched with the above routes and shows 404 page instead
  match '*a', :to => 'errors#routing'
end

app/views/shared/_content_titles.html.haml
.content-titles
  - viewing_someone_else = (current_user.blank? || !current_user?(@user))

  %ul
    - unless viewing_someone_else
      %li
        = link_to("Stream", user_stream_path(@user), :class => "lighten-to-blue")
  
    - unless viewing_someone_else
      %li.latest-activity
        - unseen_notifications_count ||= @user.notifications_count
        - if unseen_notifications_count != 0
          %span.notifications-dot><
            #{unseen_notifications_count > 100 ? "100+" : unseen_notifications_count}
            
        = link_to("Latest Activity", user_latest_activity_path(@user), :class => "lighten-to-blue")
        
        
    
    %li.dropdown{"data-dropdown" => "dropdown"}
      = link_to(viewing_someone_else ? "Channels" : "My Channels", user_channels_path(@user), :class => "dropdown-toggle lighten-to-blue")
      %ul.dropdown-menu
        - @user.channels.limit(5).each do |c|
          %li
            = link_to(user_channel_path(@user, c)) do
              - if c.featured?
                = image_tag("featured_star.png", :alt => "Featured Channel", :size => "13x13")
              - elsif c.private?
                = image_tag("private_small.png", :alt => "Private Channel", :size => "13x13")
              - else
                = image_tag("public.png", :alt => "Public Channel", :size => "13x13")
              
              = c.title
            
        %li.divider
        %li.view-all-channels
          = link_to("View All (#{@user.channels.count}) Channels", user_channels_path(@user))

    %li
      = link_to(viewing_someone_else ? "Videos" : "My Videos", user_path(@user), :class => "lighten-to-blue")

    %li
      = link_to("About", user_about_path(@user), :class => "lighten-to-blue")

app/views/shared/_error_messages.html.haml
- if klass.errors.any?
  - klass.errors.full_messages.each do |msg|
    %div{:data => {:error => "#{msg}"}}= msg

app/views/shared/_extras.html.haml
- # Google Analytics
:javascript
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-23816026-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

- # GetSatisfaction Code
:javascript
  var is_ssl = ("https:" == document.location.protocol);
  var asset_host = is_ssl ? "https://s3.amazonaws.com/getsatisfaction.com/" : "http://s3.amazonaws.com/getsatisfaction.com/";
  document.write(unescape("%3Cscript src='" + asset_host + "javascripts/feedback-v2.js' type='text/javascript'%3E%3C/script%3E"));
:javascript
  var feedback_widget_options = {};

  feedback_widget_options.display = "overlay";
  feedback_widget_options.company = "brevidy";
  feedback_widget_options.placement = "left";
  feedback_widget_options.color = "#202020";
  feedback_widget_options.style = "idea";

  var feedback_widget = new GSFN.feedback_widget(feedback_widget_options);

- # AddThis script

// Template for AddThis sharing
:javascript
  var addthis_share = {
     templates: {
        twitter: "{{title}} {{url}} (via @brevidy)"
     }
  }
  
%script{:src => "http://s7.addthis.com/js/300/addthis_widget.js#pubid=ra-4e6fbcbf4b963006#domready=1", :type => "text/javascript"}

app/views/shared/_featured_video.html.haml
.featured-video-object{"data-video-id" => featured_video.id}
  = link_to(user_video_path(get_object_owner(featured_video), featured_video)) do
    = image_tag(featured_video.get_thumbnail_url(featured_video.selected_thumbnail), :size => "190x102", :alt => featured_video.title, :class => "featured-popover", :title => featured_video.title, "data-content" => featured_video.description.blank? ? "No description given" : truncate(featured_video.description, :length => 150))
    %i.play-icon
      = image_tag("play_small.png", :alt => "Play", :size => "45x34")

app/views/shared/_header.html.haml
.topbar
  .topbar-inner
    .container
      .static-links
        = link_to(image_tag("brevidy_rgb_white.png", :size => "135x35", :alt => "Brevidy - The Soul of Video"), signed_in? ? user_stream_path(current_user) : :root, :class => "brand")
    
        %form.pull-left{:action => video_search_path, :method => "get"}
          %input{:name => "q", :placeholder => "Search public videos", :type => "text"}/
          %span.search
            %button{:type => "submit", :value => "Go"}
        
        - if signed_in?
          %ul.nav
            %li
              = link_to("Explore", explore_path)
            %li
              = link_to("Upload", new_user_video_path(current_user))
            %li
              = link_to("Share a Link", user_share_dialog_path(current_user), :remote => true, "data-method" => "GET")
            %li
              = link_to("Invite", user_invitations_path(current_user))
      
      .dynamic-links
        - if signed_in?
          %ul.nav.secondary-nav
            %li.dropdown{"data-dropdown" => "dropdown"}
              = link_to(user_path(current_user), :class => "dropdown-toggle") do
                %span#user-image
                  = image_tag("#{current_user.image.blank? ? 'default_user_35px.jpg' : current_user.image_url(:small_profile) }", :alt => "#{current_user.name}", :size => "35x35")
                %span#username
                  = current_user.username
              %ul.dropdown-menu
                %li
                  = link_to("My Channels", user_channels_path(current_user))
                %li
                  = link_to("Account Settings", user_account_path(current_user))
                %li
                  = link_to("Find People", find_people_path)
                %li
                  = link_to("Help", "http://getsatisfaction.com/brevidy", :target => "_blank")
                %li.divider
                %li
                  = link_to("Logout", logout_path, :remote => true, "data-method" => "DELETE")
        - else
          %ul.nav.secondary-nav
            %li
              = link_to("Explore", explore_path)
            %li.vertical-divider 
            %li
              = link_to("Sign up", signup_path)
            %li.vertical-divider
            %li
              = link_to("Login", login_path)
            

app/views/shared/_infinite_scrolling.html.haml
- @page_has_infinite_scrolling = true
:javascript  
  // Wait until all other JS in the page has loaded to run this
  $(window).load(function(){
  
    // Hides pagination controls
    $('.pagination').hide();
    
    // Adds infinite scrolling to a page based on 'item_selector' that gets passed in
    $('.content-wrapper').infinitescroll({
      appendCallback: false, // tells the script not to scrape the HTML using the .load() method
      dataType: 'html', // sets the data response type
      navSelector  : ".pagination", // selector for the paged navigation (it will be hidden)
      nextSelector : ".pagination a.next_page", // selector for the NEXT link (to page 2)
      itemSelector : "#{item_selector}", // selector for all items you'll retrieve
      loading: {
        msgText: "LOADING MORE...",
        img: "#{image_path('ajax.gif')}"
      }
    });
    
  });

app/views/shared/_lower_navigation.haml
.footerWrapper
  %p.dark.pull-right
    = succeed " · " do
      = link_to("FAQ", faq_path, :class => "inlinelink")
    = succeed " · " do
      = link_to("Blog", "http://blog.brevidy.com", :class => "inlinelink")
    = succeed " · " do
      = link_to("Status", "http://status.brevidy.com", :class => "inlinelink")
    = succeed " · " do
      = link_to("Contact", contact_path, :class => "inlinelink")
    = succeed " · " do
      = link_to("Terms", tos_path, :class => "inlinelink")
    = succeed " · " do
      = link_to("Privacy", privacy_path, :class => "inlinelink")
    Brevidy LLC, © 2012

app/views/shared/_scroll_to_content_wrapper.html.haml
:javascript
  $(window).load(function() {
    $.smoothScroll({
      offset: -50,
      scrollTarget: '.content-wrapper',
      speed: 500
    });
  });

app/views/shared/_select_birthday.html.haml
%select.medium.birthday_month{:name => "birthday_month"}
  = options_for_select((1..12).map {|m| [Date::MONTHNAMES[m], m]})
%select.medium.birthday_day{:name => "birthday_day"}
  = options_for_select((1..31))
%select.medium.birthday_year{:name => "birthday_year"}
  = options_for_select((1901..Date.today.year).to_a.reverse)
  
- # Set the select values if they were passed in
- if defined?(the_month) 
  :javascript
    $('select.birthday_month').val("#{the_month}");
    $('select.birthday_day').val("#{the_day}");
    $('select.birthday_year').val("#{the_year}");